const data = [
  { name: "Rahul", age: 20, marks: 95, city: "Delhi" },
  { name: "Priya", age: 22, marks: 92, city: "Mumbai" },
  { name: "Amit", age: 21, marks: 85, city: "Chandigarh" },
  { name: "Neha", age: 23, marks: 88, city: "Pune" },
  { name: "Rohit", age: 20, marks: 91, city: "Delhi" },
  { name: "Simran", age: 22, marks: 78, city: "Amritsar" },
  { name: "Karan", age: 21, marks: 96, city: "Ludhiana" },
  { name: "Anjali", age: 23, marks: 89, city: "Jaipur" },

  { name: "Vikas", age: 24, marks: 67, city: "Delhi" },
  { name: "Pooja", age: 20, marks: 73, city: "Mumbai" },
  { name: "Arjun", age: 21, marks: 82, city: "Chandigarh" },
  { name: "Meena", age: 22, marks: 90, city: "Pune" },
  { name: "Deepak", age: 23, marks: 94, city: "Delhi" },
  { name: "Ritika", age: 20, marks: 86, city: "Amritsar" },
  { name: "Sandeep", age: 21, marks: 76, city: "Ludhiana" },
  { name: "Kavita", age: 22, marks: 81, city: "Jaipur" },

  { name: "Manish", age: 23, marks: 69, city: "Delhi" },
  { name: "Nisha", age: 21, marks: 88, city: "Mumbai" },
  { name: "Tarun", age: 20, marks: 91, city: "Chandigarh" },
  { name: "Sneha", age: 22, marks: 93, city: "Pune" },
  { name: "Ajay", age: 24, marks: 72, city: "Delhi" },
  { name: "Preeti", age: 23, marks: 84, city: "Amritsar" },
  { name: "Varun", age: 21, marks: 79, city: "Ludhiana" },
  { name: "Shreya", age: 20, marks: 87, city: "Jaipur" },

  { name: "Yash", age: 22, marks: 90, city: "Delhi" },
  { name: "Komal", age: 21, marks: 83, city: "Mumbai" },
  { name: "Gaurav", age: 23, marks: 77, city: "Chandigarh" },
  { name: "Divya", age: 24, marks: 92, city: "Pune" },
  { name: "Ankit", age: 20, marks: 68, city: "Delhi" },
  { name: "Riya", age: 22, marks: 95, city: "Amritsar" },
  { name: "Harsh", age: 21, marks: 80, city: "Ludhiana" },
  { name: "Payal", age: 23, marks: 89, city: "Jaipur" },

  { name: "Abhishek", age: 24, marks: 91, city: "Delhi" },
  { name: "Isha", age: 20, marks: 85, city: "Mumbai" },
  { name: "Nikhil", age: 21, marks: 74, city: "Chandigarh" },
  { name: "Tanya", age: 22, marks: 88, city: "Pune" },
  { name: "Ramesh", age: 23, marks: 66, city: "Delhi" },
  { name: "Sonia", age: 21, marks: 93, city: "Amritsar" },
  { name: "Kunal", age: 22, marks: 82, city: "Ludhiana" },
  { name: "Monika", age: 20, marks: 90, city: "Jaipur" },

  { name: "Pankaj", age: 23, marks: 78, city: "Delhi" },
  { name: "Seema", age: 24, marks: 87, city: "Mumbai" },
  { name: "Lokesh", age: 21, marks: 92, city: "Chandigarh" },
  { name: "Bhavna", age: 22, marks: 81, city: "Pune" },
  { name: "Jatin", age: 20, marks: 75, city: "Delhi" },
  { name: "Alka", age: 23, marks: 89, city: "Amritsar" },
  { name: "Naveen", age: 21, marks: 94, city: "Ludhiana" },
  { name: "Rekha", age: 22, marks: 86, city: "Jaipur" }
]
export default { data };
